name: Test backward compatibility

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-backward-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install AsyncAPI CLI
        run: |
          npm install -g @asyncapi/cli
          asyncapi --version

      - name: Running AsyncAPI spec diff action
        run: asyncapi diff ./asyncapi.old.yaml ./asyncapi.yaml -o breaking-changes-override.json -t breaking -f json